### PR TITLE
feat: modify text block

### PR DESCRIPTION
**Pull request by hannahouazzane**
Updates text in the right hand column.
Adds a blockquote element with styles.
Modifies styling on the two columns

### CODE REVIEW

**Review by rosejbon — APPROVED** [review]
Love to see a blockquote in the wild 🔭

**Comment by harryharrold** [comment]
> Love to see a blockquote in the wild 🔭

Proper sematic!

**Review by harryharrold — COMMENTED** [review]
Should the <cite> encompass the job title as well as the organisation, strictly speaking?

**Comment by rosejbon** [comment]
> Should the `cite` encompass the job title as well as the organisation, strictly speaking?

On further reading it looks like the `<cite>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is only used to mark up the title of a cited creative work like books, publications etc. So we might not even need it in this context

**Comment by hannahouazzane** [comment]
> > Should the `cite` encompass the job title as well as the organisation, strictly speaking?
> 
> On further reading it looks like the `<cite>` [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is only used to mark up the title of a cited creative work like books, publications etc. So we might not even need it in this context

Thank you @rosejbon @harryharrold , changed it :)

**Pull request merged**
